package com.jmz.qyyl.model.example;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class SystemDBbakExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table system_dbbak
     *
     * @mbggenerated Tue Nov 28 13:38:48 CST 2017
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table system_dbbak
     *
     * @mbggenerated Tue Nov 28 13:38:48 CST 2017
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table system_dbbak
     *
     * @mbggenerated Tue Nov 28 13:38:48 CST 2017
     */
    protected List<Criteria> oredCriteria;

    /**
     * generated by VrviewCommentGenerator.
     *
     * @mbggenerated Tue Nov 28 13:38:48 CST 2017
     */
    public SystemDBbakExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * generated by VrviewCommentGenerator.
     * @param orderByClause orderByClause
     *
     * @mbggenerated Tue Nov 28 13:38:48 CST 2017
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * generated by VrviewCommentGenerator.
     * @return java.lang.String
     *
     * @mbggenerated Tue Nov 28 13:38:48 CST 2017
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * generated by VrviewCommentGenerator.
     * @param distinct distinct
     *
     * @mbggenerated Tue Nov 28 13:38:48 CST 2017
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * generated by VrviewCommentGenerator.
     * @return boolean
     *
     * @mbggenerated Tue Nov 28 13:38:48 CST 2017
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * generated by VrviewCommentGenerator.
     * @return java.util.List<Criteria>
     *
     * @mbggenerated Tue Nov 28 13:38:48 CST 2017
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * generated by VrviewCommentGenerator.
     * @param criteria criteria
     *
     * @mbggenerated Tue Nov 28 13:38:48 CST 2017
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * generated by VrviewCommentGenerator.
     * @return Criteria
     *
     * @mbggenerated Tue Nov 28 13:38:48 CST 2017
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * generated by VrviewCommentGenerator.
     * @return Criteria
     *
     * @mbggenerated Tue Nov 28 13:38:48 CST 2017
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * generated by VrviewCommentGenerator.
     * @return Criteria
     *
     * @mbggenerated Tue Nov 28 13:38:48 CST 2017
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * generated by VrviewCommentGenerator.
     *
     * @mbggenerated Tue Nov 28 13:38:48 CST 2017
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table system_dbbak
     *
     * @mbggenerated Tue Nov 28 13:38:48 CST 2017
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andBakIdIsNull() {
            addCriterion("bak_id is null");
            return (Criteria) this;
        }

        public Criteria andBakIdIsNotNull() {
            addCriterion("bak_id is not null");
            return (Criteria) this;
        }

        public Criteria andBakIdEqualTo(Integer value) {
            addCriterion("bak_id =", value, "bakId");
            return (Criteria) this;
        }

        public Criteria andBakIdNotEqualTo(Integer value) {
            addCriterion("bak_id <>", value, "bakId");
            return (Criteria) this;
        }

        public Criteria andBakIdGreaterThan(Integer value) {
            addCriterion("bak_id >", value, "bakId");
            return (Criteria) this;
        }

        public Criteria andBakIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("bak_id >=", value, "bakId");
            return (Criteria) this;
        }

        public Criteria andBakIdLessThan(Integer value) {
            addCriterion("bak_id <", value, "bakId");
            return (Criteria) this;
        }

        public Criteria andBakIdLessThanOrEqualTo(Integer value) {
            addCriterion("bak_id <=", value, "bakId");
            return (Criteria) this;
        }

        public Criteria andBakIdIn(List<Integer> values) {
            addCriterion("bak_id in", values, "bakId");
            return (Criteria) this;
        }

        public Criteria andBakIdNotIn(List<Integer> values) {
            addCriterion("bak_id not in", values, "bakId");
            return (Criteria) this;
        }

        public Criteria andBakIdBetween(Integer value1, Integer value2) {
            addCriterion("bak_id between", value1, value2, "bakId");
            return (Criteria) this;
        }

        public Criteria andBakIdNotBetween(Integer value1, Integer value2) {
            addCriterion("bak_id not between", value1, value2, "bakId");
            return (Criteria) this;
        }

        public Criteria andDbNameIsNull() {
            addCriterion("db_name is null");
            return (Criteria) this;
        }

        public Criteria andDbNameIsNotNull() {
            addCriterion("db_name is not null");
            return (Criteria) this;
        }

        public Criteria andDbNameEqualTo(String value) {
            addCriterion("db_name =", value, "dbName");
            return (Criteria) this;
        }

        public Criteria andDbNameNotEqualTo(String value) {
            addCriterion("db_name <>", value, "dbName");
            return (Criteria) this;
        }

        public Criteria andDbNameGreaterThan(String value) {
            addCriterion("db_name >", value, "dbName");
            return (Criteria) this;
        }

        public Criteria andDbNameGreaterThanOrEqualTo(String value) {
            addCriterion("db_name >=", value, "dbName");
            return (Criteria) this;
        }

        public Criteria andDbNameLessThan(String value) {
            addCriterion("db_name <", value, "dbName");
            return (Criteria) this;
        }

        public Criteria andDbNameLessThanOrEqualTo(String value) {
            addCriterion("db_name <=", value, "dbName");
            return (Criteria) this;
        }

        public Criteria andDbNameLike(String value) {
            addCriterion("db_name like", value, "dbName");
            return (Criteria) this;
        }

        public Criteria andDbNameNotLike(String value) {
            addCriterion("db_name not like", value, "dbName");
            return (Criteria) this;
        }

        public Criteria andDbNameIn(List<String> values) {
            addCriterion("db_name in", values, "dbName");
            return (Criteria) this;
        }

        public Criteria andDbNameNotIn(List<String> values) {
            addCriterion("db_name not in", values, "dbName");
            return (Criteria) this;
        }

        public Criteria andDbNameBetween(String value1, String value2) {
            addCriterion("db_name between", value1, value2, "dbName");
            return (Criteria) this;
        }

        public Criteria andDbNameNotBetween(String value1, String value2) {
            addCriterion("db_name not between", value1, value2, "dbName");
            return (Criteria) this;
        }

        public Criteria andDbBakNameIsNull() {
            addCriterion("db_bak_name is null");
            return (Criteria) this;
        }

        public Criteria andDbBakNameIsNotNull() {
            addCriterion("db_bak_name is not null");
            return (Criteria) this;
        }

        public Criteria andDbBakNameEqualTo(String value) {
            addCriterion("db_bak_name =", value, "dbBakName");
            return (Criteria) this;
        }

        public Criteria andDbBakNameNotEqualTo(String value) {
            addCriterion("db_bak_name <>", value, "dbBakName");
            return (Criteria) this;
        }

        public Criteria andDbBakNameGreaterThan(String value) {
            addCriterion("db_bak_name >", value, "dbBakName");
            return (Criteria) this;
        }

        public Criteria andDbBakNameGreaterThanOrEqualTo(String value) {
            addCriterion("db_bak_name >=", value, "dbBakName");
            return (Criteria) this;
        }

        public Criteria andDbBakNameLessThan(String value) {
            addCriterion("db_bak_name <", value, "dbBakName");
            return (Criteria) this;
        }

        public Criteria andDbBakNameLessThanOrEqualTo(String value) {
            addCriterion("db_bak_name <=", value, "dbBakName");
            return (Criteria) this;
        }

        public Criteria andDbBakNameLike(String value) {
            addCriterion("db_bak_name like", value, "dbBakName");
            return (Criteria) this;
        }

        public Criteria andDbBakNameNotLike(String value) {
            addCriterion("db_bak_name not like", value, "dbBakName");
            return (Criteria) this;
        }

        public Criteria andDbBakNameIn(List<String> values) {
            addCriterion("db_bak_name in", values, "dbBakName");
            return (Criteria) this;
        }

        public Criteria andDbBakNameNotIn(List<String> values) {
            addCriterion("db_bak_name not in", values, "dbBakName");
            return (Criteria) this;
        }

        public Criteria andDbBakNameBetween(String value1, String value2) {
            addCriterion("db_bak_name between", value1, value2, "dbBakName");
            return (Criteria) this;
        }

        public Criteria andDbBakNameNotBetween(String value1, String value2) {
            addCriterion("db_bak_name not between", value1, value2, "dbBakName");
            return (Criteria) this;
        }

        public Criteria andDbSizeIsNull() {
            addCriterion("db_size is null");
            return (Criteria) this;
        }

        public Criteria andDbSizeIsNotNull() {
            addCriterion("db_size is not null");
            return (Criteria) this;
        }

        public Criteria andDbSizeEqualTo(Integer value) {
            addCriterion("db_size =", value, "dbSize");
            return (Criteria) this;
        }

        public Criteria andDbSizeNotEqualTo(Integer value) {
            addCriterion("db_size <>", value, "dbSize");
            return (Criteria) this;
        }

        public Criteria andDbSizeGreaterThan(Integer value) {
            addCriterion("db_size >", value, "dbSize");
            return (Criteria) this;
        }

        public Criteria andDbSizeGreaterThanOrEqualTo(Integer value) {
            addCriterion("db_size >=", value, "dbSize");
            return (Criteria) this;
        }

        public Criteria andDbSizeLessThan(Integer value) {
            addCriterion("db_size <", value, "dbSize");
            return (Criteria) this;
        }

        public Criteria andDbSizeLessThanOrEqualTo(Integer value) {
            addCriterion("db_size <=", value, "dbSize");
            return (Criteria) this;
        }

        public Criteria andDbSizeIn(List<Integer> values) {
            addCriterion("db_size in", values, "dbSize");
            return (Criteria) this;
        }

        public Criteria andDbSizeNotIn(List<Integer> values) {
            addCriterion("db_size not in", values, "dbSize");
            return (Criteria) this;
        }

        public Criteria andDbSizeBetween(Integer value1, Integer value2) {
            addCriterion("db_size between", value1, value2, "dbSize");
            return (Criteria) this;
        }

        public Criteria andDbSizeNotBetween(Integer value1, Integer value2) {
            addCriterion("db_size not between", value1, value2, "dbSize");
            return (Criteria) this;
        }

        public Criteria andDbBakTypeIsNull() {
            addCriterion("db_bak_type is null");
            return (Criteria) this;
        }

        public Criteria andDbBakTypeIsNotNull() {
            addCriterion("db_bak_type is not null");
            return (Criteria) this;
        }

        public Criteria andDbBakTypeEqualTo(Integer value) {
            addCriterion("db_bak_type =", value, "dbBakType");
            return (Criteria) this;
        }

        public Criteria andDbBakTypeNotEqualTo(Integer value) {
            addCriterion("db_bak_type <>", value, "dbBakType");
            return (Criteria) this;
        }

        public Criteria andDbBakTypeGreaterThan(Integer value) {
            addCriterion("db_bak_type >", value, "dbBakType");
            return (Criteria) this;
        }

        public Criteria andDbBakTypeGreaterThanOrEqualTo(Integer value) {
            addCriterion("db_bak_type >=", value, "dbBakType");
            return (Criteria) this;
        }

        public Criteria andDbBakTypeLessThan(Integer value) {
            addCriterion("db_bak_type <", value, "dbBakType");
            return (Criteria) this;
        }

        public Criteria andDbBakTypeLessThanOrEqualTo(Integer value) {
            addCriterion("db_bak_type <=", value, "dbBakType");
            return (Criteria) this;
        }

        public Criteria andDbBakTypeIn(List<Integer> values) {
            addCriterion("db_bak_type in", values, "dbBakType");
            return (Criteria) this;
        }

        public Criteria andDbBakTypeNotIn(List<Integer> values) {
            addCriterion("db_bak_type not in", values, "dbBakType");
            return (Criteria) this;
        }

        public Criteria andDbBakTypeBetween(Integer value1, Integer value2) {
            addCriterion("db_bak_type between", value1, value2, "dbBakType");
            return (Criteria) this;
        }

        public Criteria andDbBakTypeNotBetween(Integer value1, Integer value2) {
            addCriterion("db_bak_type not between", value1, value2, "dbBakType");
            return (Criteria) this;
        }

        public Criteria andDbBakTimeIsNull() {
            addCriterion("db_bak_time is null");
            return (Criteria) this;
        }

        public Criteria andDbBakTimeIsNotNull() {
            addCriterion("db_bak_time is not null");
            return (Criteria) this;
        }

        public Criteria andDbBakTimeEqualTo(Date value) {
            addCriterion("db_bak_time =", value, "dbBakTime");
            return (Criteria) this;
        }

        public Criteria andDbBakTimeNotEqualTo(Date value) {
            addCriterion("db_bak_time <>", value, "dbBakTime");
            return (Criteria) this;
        }

        public Criteria andDbBakTimeGreaterThan(Date value) {
            addCriterion("db_bak_time >", value, "dbBakTime");
            return (Criteria) this;
        }

        public Criteria andDbBakTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("db_bak_time >=", value, "dbBakTime");
            return (Criteria) this;
        }

        public Criteria andDbBakTimeLessThan(Date value) {
            addCriterion("db_bak_time <", value, "dbBakTime");
            return (Criteria) this;
        }

        public Criteria andDbBakTimeLessThanOrEqualTo(Date value) {
            addCriterion("db_bak_time <=", value, "dbBakTime");
            return (Criteria) this;
        }

        public Criteria andDbBakTimeIn(List<Date> values) {
            addCriterion("db_bak_time in", values, "dbBakTime");
            return (Criteria) this;
        }

        public Criteria andDbBakTimeNotIn(List<Date> values) {
            addCriterion("db_bak_time not in", values, "dbBakTime");
            return (Criteria) this;
        }

        public Criteria andDbBakTimeBetween(Date value1, Date value2) {
            addCriterion("db_bak_time between", value1, value2, "dbBakTime");
            return (Criteria) this;
        }

        public Criteria andDbBakTimeNotBetween(Date value1, Date value2) {
            addCriterion("db_bak_time not between", value1, value2, "dbBakTime");
            return (Criteria) this;
        }

        public Criteria andDbBakUserIsNull() {
            addCriterion("db_bak_user is null");
            return (Criteria) this;
        }

        public Criteria andDbBakUserIsNotNull() {
            addCriterion("db_bak_user is not null");
            return (Criteria) this;
        }

        public Criteria andDbBakUserEqualTo(String value) {
            addCriterion("db_bak_user =", value, "dbBakUser");
            return (Criteria) this;
        }

        public Criteria andDbBakUserNotEqualTo(String value) {
            addCriterion("db_bak_user <>", value, "dbBakUser");
            return (Criteria) this;
        }

        public Criteria andDbBakUserGreaterThan(String value) {
            addCriterion("db_bak_user >", value, "dbBakUser");
            return (Criteria) this;
        }

        public Criteria andDbBakUserGreaterThanOrEqualTo(String value) {
            addCriterion("db_bak_user >=", value, "dbBakUser");
            return (Criteria) this;
        }

        public Criteria andDbBakUserLessThan(String value) {
            addCriterion("db_bak_user <", value, "dbBakUser");
            return (Criteria) this;
        }

        public Criteria andDbBakUserLessThanOrEqualTo(String value) {
            addCriterion("db_bak_user <=", value, "dbBakUser");
            return (Criteria) this;
        }

        public Criteria andDbBakUserLike(String value) {
            addCriterion("db_bak_user like", value, "dbBakUser");
            return (Criteria) this;
        }

        public Criteria andDbBakUserNotLike(String value) {
            addCriterion("db_bak_user not like", value, "dbBakUser");
            return (Criteria) this;
        }

        public Criteria andDbBakUserIn(List<String> values) {
            addCriterion("db_bak_user in", values, "dbBakUser");
            return (Criteria) this;
        }

        public Criteria andDbBakUserNotIn(List<String> values) {
            addCriterion("db_bak_user not in", values, "dbBakUser");
            return (Criteria) this;
        }

        public Criteria andDbBakUserBetween(String value1, String value2) {
            addCriterion("db_bak_user between", value1, value2, "dbBakUser");
            return (Criteria) this;
        }

        public Criteria andDbBakUserNotBetween(String value1, String value2) {
            addCriterion("db_bak_user not between", value1, value2, "dbBakUser");
            return (Criteria) this;
        }

        public Criteria andDbBakNoteIsNull() {
            addCriterion("db_bak_note is null");
            return (Criteria) this;
        }

        public Criteria andDbBakNoteIsNotNull() {
            addCriterion("db_bak_note is not null");
            return (Criteria) this;
        }

        public Criteria andDbBakNoteEqualTo(String value) {
            addCriterion("db_bak_note =", value, "dbBakNote");
            return (Criteria) this;
        }

        public Criteria andDbBakNoteNotEqualTo(String value) {
            addCriterion("db_bak_note <>", value, "dbBakNote");
            return (Criteria) this;
        }

        public Criteria andDbBakNoteGreaterThan(String value) {
            addCriterion("db_bak_note >", value, "dbBakNote");
            return (Criteria) this;
        }

        public Criteria andDbBakNoteGreaterThanOrEqualTo(String value) {
            addCriterion("db_bak_note >=", value, "dbBakNote");
            return (Criteria) this;
        }

        public Criteria andDbBakNoteLessThan(String value) {
            addCriterion("db_bak_note <", value, "dbBakNote");
            return (Criteria) this;
        }

        public Criteria andDbBakNoteLessThanOrEqualTo(String value) {
            addCriterion("db_bak_note <=", value, "dbBakNote");
            return (Criteria) this;
        }

        public Criteria andDbBakNoteLike(String value) {
            addCriterion("db_bak_note like", value, "dbBakNote");
            return (Criteria) this;
        }

        public Criteria andDbBakNoteNotLike(String value) {
            addCriterion("db_bak_note not like", value, "dbBakNote");
            return (Criteria) this;
        }

        public Criteria andDbBakNoteIn(List<String> values) {
            addCriterion("db_bak_note in", values, "dbBakNote");
            return (Criteria) this;
        }

        public Criteria andDbBakNoteNotIn(List<String> values) {
            addCriterion("db_bak_note not in", values, "dbBakNote");
            return (Criteria) this;
        }

        public Criteria andDbBakNoteBetween(String value1, String value2) {
            addCriterion("db_bak_note between", value1, value2, "dbBakNote");
            return (Criteria) this;
        }

        public Criteria andDbBakNoteNotBetween(String value1, String value2) {
            addCriterion("db_bak_note not between", value1, value2, "dbBakNote");
            return (Criteria) this;
        }

        public Criteria andDbBakPathIsNull() {
            addCriterion("db_bak_path is null");
            return (Criteria) this;
        }

        public Criteria andDbBakPathIsNotNull() {
            addCriterion("db_bak_path is not null");
            return (Criteria) this;
        }

        public Criteria andDbBakPathEqualTo(String value) {
            addCriterion("db_bak_path =", value, "dbBakPath");
            return (Criteria) this;
        }

        public Criteria andDbBakPathNotEqualTo(String value) {
            addCriterion("db_bak_path <>", value, "dbBakPath");
            return (Criteria) this;
        }

        public Criteria andDbBakPathGreaterThan(String value) {
            addCriterion("db_bak_path >", value, "dbBakPath");
            return (Criteria) this;
        }

        public Criteria andDbBakPathGreaterThanOrEqualTo(String value) {
            addCriterion("db_bak_path >=", value, "dbBakPath");
            return (Criteria) this;
        }

        public Criteria andDbBakPathLessThan(String value) {
            addCriterion("db_bak_path <", value, "dbBakPath");
            return (Criteria) this;
        }

        public Criteria andDbBakPathLessThanOrEqualTo(String value) {
            addCriterion("db_bak_path <=", value, "dbBakPath");
            return (Criteria) this;
        }

        public Criteria andDbBakPathLike(String value) {
            addCriterion("db_bak_path like", value, "dbBakPath");
            return (Criteria) this;
        }

        public Criteria andDbBakPathNotLike(String value) {
            addCriterion("db_bak_path not like", value, "dbBakPath");
            return (Criteria) this;
        }

        public Criteria andDbBakPathIn(List<String> values) {
            addCriterion("db_bak_path in", values, "dbBakPath");
            return (Criteria) this;
        }

        public Criteria andDbBakPathNotIn(List<String> values) {
            addCriterion("db_bak_path not in", values, "dbBakPath");
            return (Criteria) this;
        }

        public Criteria andDbBakPathBetween(String value1, String value2) {
            addCriterion("db_bak_path between", value1, value2, "dbBakPath");
            return (Criteria) this;
        }

        public Criteria andDbBakPathNotBetween(String value1, String value2) {
            addCriterion("db_bak_path not between", value1, value2, "dbBakPath");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table system_dbbak
     *
     * @mbggenerated do_not_delete_during_merge Tue Nov 28 13:38:48 CST 2017
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table system_dbbak
     *
     * @mbggenerated Tue Nov 28 13:38:48 CST 2017
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}