package com.jmz.qyyl.dao;

import com.jmz.qyyl.model.SystemDBbak;
import com.jmz.qyyl.model.example.SystemDBbakExample;
import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;

import javax.annotation.Resource;
import java.util.List;
import java.util.Map;

//@Mapper
public interface SystemDBbakMapper {
    /**
     * generated by VrviewCommentGenerator.
     * @param example example
     * @return int
     *
     * @mbggenerated Tue Nov 28 13:38:48 CST 2017
     */
    int countByExample(SystemDBbakExample example);

    /**
     * generated by VrviewCommentGenerator.
     * @param example example
     * @return int
     *
     * @mbggenerated Tue Nov 28 13:38:48 CST 2017
     */
    int deleteByExample(SystemDBbakExample example);

    /**
     * generated by VrviewCommentGenerator.
     * @param bakId bakId
     * @return int
     *
     * @mbggenerated Tue Nov 28 13:38:48 CST 2017
     */
    int deleteByPrimaryKey(Integer bakId);

    /**
     * generated by VrviewCommentGenerator.
     * @param record record
     * @return int
     *
     * @mbggenerated Tue Nov 28 13:38:48 CST 2017
     */
    int insert(SystemDBbak record);

    /**
     * generated by VrviewCommentGenerator.
     * @param record record
     * @return int
     *
     * @mbggenerated Tue Nov 28 13:38:48 CST 2017
     */
    int insertSelective(SystemDBbak record);

    /**
     * generated by VrviewCommentGenerator.
     * @param example example
     * @return java.util.List<com.jmz.iexchange.model.SystemDBbak>
     *
     * @mbggenerated Tue Nov 28 13:38:48 CST 2017
     */
    List<SystemDBbak> selectByExample(SystemDBbakExample example);

    /**
     * generated by VrviewCommentGenerator.
     * @param bakId bakId
     * @return com.jmz.iexchange.model.SystemDBbak
     *
     * @mbggenerated Tue Nov 28 13:38:48 CST 2017
     */
    SystemDBbak selectByPrimaryKey(Integer bakId);

    /**
     * generated by VrviewCommentGenerator.
     * @param record record
     * @param record record * @param example example
     * @return int
     *
     * @mbggenerated Tue Nov 28 13:38:48 CST 2017
     */
    int updateByExampleSelective(@Param("record") SystemDBbak record, @Param("example") SystemDBbakExample example);

    /**
     * generated by VrviewCommentGenerator.
     * @param record record
     * @param record record * @param example example
     * @return int
     *
     * @mbggenerated Tue Nov 28 13:38:48 CST 2017
     */
    int updateByExample(@Param("record") SystemDBbak record, @Param("example") SystemDBbakExample example);

    /**
     * generated by VrviewCommentGenerator.
     * @param record record
     * @return int
     *
     * @mbggenerated Tue Nov 28 13:38:48 CST 2017
     */
    int updateByPrimaryKeySelective(SystemDBbak record);

    /**
     * generated by VrviewCommentGenerator.
     * @param record record
     * @return int
     *
     * @mbggenerated Tue Nov 28 13:38:48 CST 2017
     */
    int updateByPrimaryKey(SystemDBbak record);

    List queryByCondition(Map map);

    int countByCondtion(Map map);
}